{{- if .Values.persistentApps.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-populate-apps-%s" (include "erpnext.fullname" .) (now | date "20060102150405") }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: populate-apps
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              echo "Checking apps volume..."
              if [ ! -d /mnt/apps/frappe ]; then
                echo "Copying apps to /mnt/apps"
                cp -r /home/frappe/frappe-bench/apps/* /mnt/apps/
                cp -r /home/frappe/frappe-bench/env/* /mnt/env/
                echo -e "frappe\nerpnext" > /mnt/apps/apps.txt
                echo "App volume initialized."
              else
                echo "App volume already initialized. Skipping copy."
              fi
          volumeMounts:
            - name: apps
              mountPath: /mnt/apps
            - name: env
              mountPath: /mnt/env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.persistentApps.resources | nindent 12 }}
      volumes:
        - name: apps
          persistentVolumeClaim:
            claimName: {{ .Values.persistentApps.existingClaim | default (printf "%s-apps" (include "erpnext.fullname" .)) }}
        - name: env
          persistentVolumeClaim:
            claimName: {{ .Values.persistentEnv.existingClaim | default (printf "%s-env" (include "erpnext.fullname" .)) }}
      {{- with .Values.persistentApps.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.persistentApps.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.persistentApps.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
